version: 1
build:
  binary: ochaind
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: michael
  coins:
  - 10000000nom
- name: charles
  coins:
  - 10000000nom
- name: spout
  coins:
  - 10000000nom
faucet:
  name: spout
  coins:
  - 10nom
  coins_max:
  - 1000nom
  host: 0.0.0.0:4500
  port: 4500
client:
  vuex:
    path: vue/src/store
genesis:
  app_state:
    staking:
      params:
        bond_denom: nom
validators:
- name: charles
  bonded: 10000000nom
  app:
    api:
      address: :1317
    grpc:
      address: :9091
  config:
    p2p:
      laddr: :26658
    rpc:
      laddr: :26657
      pprof_laddr: :6061
